version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"   # Browser (HTTP)
      - "7687:7687"   # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"   # Redis
      - "8001:8001"   # RedisInsight UI
    restart: unless-stopped
    # environment:
    #   - REDIS_ARGS=--requirepass redispassword

volumes:
  redis-data: